app:
  scrapper-base-url: http://localhost:8080
  retry:
    max-attempts: 5
    status-codes: [ 500, 502, 503 ]
    policy: CONSTANT
    step: 0s

kafka:
  consumer:
    bootstrapServers: http://localhost:29092
    groupId: tracker-bot
    autoOffsetReset: earliest
    maxPollIntervalMs: 300_000
    enableAutoCommit: false
    concurrency: 1
    backoff:
      interval: 1s
      max-attempts: 3
  producer:
    bootstrapServers: http://localhost:29092
    clientId: bot
    acksMode: all
    deliveryTimeout: 60s
    lingerMs: 2000
    batchSize: 100_000
    maxInFlightPerConnection: 5
    enableIdempotence: true

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

management:
  server:
    port: 7090
  endpoints:
    web:
      base-path: "/"
      exposure:
        include: info, health, prometheus
      path-mapping:
        prometheus: "/metrics"
  metrics:
    tags:
      application: '${spring.application.name}'

springdoc:
  swagger-ui:
    path: /swagger-ui

logging:
  config: classpath:log4j2-plain.xml
